version: '3.9'

services:
  rustapp:
    # add your own container here
    container_name: rustapp
      # image: veer15/rustapp:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    ports:
      - '8080:8080'
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgdata:
    container_name: pgdata
    image: postgres:12
    command: "true" # A no-op command to keep the container running
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}

